USE PARQUEADERO;

CREATE TABLE ENTRADA(

CODOC INT(50),
NOMBRE NVARCHAR(50),
APELLIDO NVARCHAR(50),
PLACA NVARCHAR(50),
TIPVEHI NVARCHAR(50),
HORAING TIME,
HORASAL TIME
)

CREATE TABLE INFORMACIONENTRADA (
CUPDISPO INT (50)
)

CREATE TABLE INFORMACIONSALIDA (
SALPROX INT (50)
)

SELECT * FROM INFORMACION
SELECT * FROM ENTRADA

USE PARQUEADERO

INSERT INTO ENTRADA VALUES('1012411247', 'ANDRES', 'GONZALEZ', 'UGB01D', 'MOTO', '17:25:06', '20:40:36')

SELECT * FROM ENTRADA
